name: macOS Build and Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build and Test macOS app
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: List Xcode schemes
        run: |
          xcodebuild -list -project McFind.xcodeproj
      
      - name: Build macOS app
        run: |
          xcodebuild build \
            -project McFind.xcodeproj \
            -scheme McFind \
            -configuration Debug \
            -destination "platform=macOS"
      
      - name: Test macOS app
        run: |
          xcodebuild test \
            -project McFind.xcodeproj \
            -scheme McFind \
            -configuration Debug \
            -destination "platform=macOS"
